import '../entities/achievement.dart';

/// فهرست دستاوردهای اپلیکیشن.
///
/// دستاوردها در کد تعریف شده‌اند (نه در فایل محتوا) چون به منطق اپ گره
/// خورده‌اند؛ اما تعریف‌شان داده‌محور است و افزودن مورد تازه فقط یک سطر است.
class AchievementCatalog {
  const AchievementCatalog._();

  static const List<Achievement> all = <Achievement>[
    Achievement(
      id: 'first_word',
      title: 'نخستین قدم',
      description: 'اولین واژه‌ات را شروع کن',
      metric: AchievementMetric.wordsStarted,
      target: 1,
      emoji: '🌱',
      xpReward: 20,
      tier: 1,
    ),
    Achievement(
      id: 'words_50',
      title: 'پنجاه واژه',
      description: '۵۰ واژه را وارد برنامه‌ی یادگیری کن',
      metric: AchievementMetric.wordsStarted,
      target: 50,
      emoji: '📚',
      xpReward: 80,
      tier: 1,
    ),
    Achievement(
      id: 'words_200',
      title: 'دویست واژه',
      description: '۲۰۰ واژه را شروع کن',
      metric: AchievementMetric.wordsStarted,
      target: 200,
      emoji: '📖',
      xpReward: 200,
      tier: 2,
    ),
    Achievement(
      id: 'words_500',
      title: 'پانصد واژه',
      description: '۵۰۰ واژه را شروع کن',
      metric: AchievementMetric.wordsStarted,
      target: 500,
      emoji: '🎓',
      xpReward: 500,
      tier: 3,
    ),
    Achievement(
      id: 'mastered_10',
      title: 'ده واژه‌ی مسلط',
      description: '۱۰ واژه را کامل به خاطر بسپار',
      metric: AchievementMetric.wordsMastered,
      target: 10,
      emoji: '💪',
      xpReward: 60,
      tier: 1,
    ),
    Achievement(
      id: 'mastered_50',
      title: 'پنجاه واژه‌ی مسلط',
      description: '۵۰ واژه را مسلط شو',
      metric: AchievementMetric.wordsMastered,
      target: 50,
      emoji: '🏅',
      xpReward: 180,
      tier: 2,
    ),
    Achievement(
      id: 'mastered_150',
      title: 'صد و پنجاه واژه‌ی مسلط',
      description: '۱۵۰ واژه را مسلط شو',
      metric: AchievementMetric.wordsMastered,
      target: 150,
      emoji: '🏆',
      xpReward: 450,
      tier: 3,
    ),
    Achievement(
      id: 'reviews_100',
      title: 'صد مرور',
      description: '۱۰۰ مرور انجام بده',
      metric: AchievementMetric.reviewsDone,
      target: 100,
      emoji: '🔁',
      xpReward: 60,
      tier: 1,
    ),
    Achievement(
      id: 'reviews_500',
      title: 'پانصد مرور',
      description: '۵۰۰ مرور انجام بده',
      metric: AchievementMetric.reviewsDone,
      target: 500,
      emoji: '♻️',
      xpReward: 200,
      tier: 2,
    ),
    Achievement(
      id: 'reviews_2000',
      title: 'مرورگر حرفه‌ای',
      description: '۲۰۰۰ مرور انجام بده',
      metric: AchievementMetric.reviewsDone,
      target: 2000,
      emoji: '🔄',
      xpReward: 600,
      tier: 3,
    ),
    Achievement(
      id: 'correct_100',
      title: 'صد پاسخ درست',
      description: '۱۰۰ پاسخ درست بده',
      metric: AchievementMetric.correctAnswers,
      target: 100,
      emoji: '✅',
      xpReward: 60,
      tier: 1,
    ),
    Achievement(
      id: 'correct_1000',
      title: 'هزار پاسخ درست',
      description: '۱۰۰۰ پاسخ درست بده',
      metric: AchievementMetric.correctAnswers,
      target: 1000,
      emoji: '🎯',
      xpReward: 300,
      tier: 3,
    ),
    Achievement(
      id: 'perfect_1',
      title: 'بی‌رقیب',
      description: 'یک جلسه را بدون هیچ غلطی تمام کن',
      metric: AchievementMetric.perfectSessions,
      target: 1,
      emoji: '🎖️',
      xpReward: 40,
      tier: 1,
    ),
    Achievement(
      id: 'perfect_10',
      title: 'بی‌نقص',
      description: '۱۰ جلسه‌ی بی‌غلط ثبت کن',
      metric: AchievementMetric.perfectSessions,
      target: 10,
      emoji: '✨',
      xpReward: 220,
      tier: 2,
    ),
    Achievement(
      id: 'streak_3',
      title: 'سه روز پیاپی',
      description: '۳ روز پشت‌سرهم مطالعه کن',
      metric: AchievementMetric.streakDays,
      target: 3,
      emoji: '🔥',
      xpReward: 40,
      tier: 1,
    ),
    Achievement(
      id: 'streak_7',
      title: 'هفت روز پیاپی',
      description: 'یک هفته‌ی کامل بدون وقفه',
      metric: AchievementMetric.streakDays,
      target: 7,
      emoji: '🗓️',
      xpReward: 100,
      tier: 1,
    ),
    Achievement(
      id: 'streak_30',
      title: 'سی روز پیاپی',
      description: '۳۰ روز پشت‌سرهم مطالعه کن',
      metric: AchievementMetric.streakDays,
      target: 30,
      emoji: '🌟',
      xpReward: 400,
      tier: 2,
    ),
    Achievement(
      id: 'streak_100',
      title: 'صد روز پیاپی',
      description: '۱۰۰ روز بدون وقفه — قهرمان واقعی',
      metric: AchievementMetric.streakDays,
      target: 100,
      emoji: '👑',
      xpReward: 1200,
      tier: 3,
    ),
    Achievement(
      id: 'xp_1000',
      title: 'هزار امتیاز',
      description: '۱۰۰۰ امتیاز تجربه جمع کن',
      metric: AchievementMetric.totalXp,
      target: 1000,
      emoji: '⚡',
      xpReward: 80,
      tier: 1,
    ),
    Achievement(
      id: 'xp_10000',
      title: 'ده هزار امتیاز',
      description: '۱۰٬۰۰۰ امتیاز تجربه جمع کن',
      metric: AchievementMetric.totalXp,
      target: 10000,
      emoji: '💫',
      xpReward: 500,
      tier: 3,
    ),
    Achievement(
      id: 'level_a2',
      title: 'قدم در A2',
      description: 'به سطح A2 برس',
      metric: AchievementMetric.levelReached,
      target: 2,
      emoji: '🧭',
      xpReward: 60,
      tier: 1,
    ),
    Achievement(
      id: 'level_b1',
      title: 'رسیدن به B1',
      description: 'به سطح B1 برس',
      metric: AchievementMetric.levelReached,
      target: 3,
      emoji: '🧭',
      xpReward: 150,
      tier: 2,
    ),
    Achievement(
      id: 'level_b2',
      title: 'رسیدن به B2',
      description: 'به سطح B2 برس',
      metric: AchievementMetric.levelReached,
      target: 4,
      emoji: '🧭',
      xpReward: 300,
      tier: 2,
    ),
    Achievement(
      id: 'level_c1',
      title: 'رسیدن به C1',
      description: 'به سطح C1 برس',
      metric: AchievementMetric.levelReached,
      target: 5,
      emoji: '🚀',
      xpReward: 600,
      tier: 3,
    ),
    Achievement(
      id: 'level_c2',
      title: 'قله‌ی C2',
      description: 'به سطح C2 برس',
      metric: AchievementMetric.levelReached,
      target: 6,
      emoji: '🏔️',
      xpReward: 1000,
      tier: 3,
    ),
    Achievement(
      id: 'challenge_1',
      title: 'قهرمان روز',
      description: 'اولین چالش روزانه را کامل کن',
      metric: AchievementMetric.challengesDone,
      target: 1,
      emoji: '🎪',
      xpReward: 30,
      tier: 1,
    ),
    Achievement(
      id: 'challenge_30',
      title: 'سی چالش',
      description: '۳۰ چالش روزانه را کامل کن',
      metric: AchievementMetric.challengesDone,
      target: 30,
      emoji: '🎠',
      xpReward: 400,
      tier: 2,
    ),
    Achievement(
      id: 'listening_50',
      title: 'گوشِ شنوا',
      description: '۵۰ پاسخ درست در تمرین شنیداری',
      metric: AchievementMetric.listeningCorrect,
      target: 50,
      emoji: '🎧',
      xpReward: 120,
      tier: 2,
    ),
    Achievement(
      id: 'typing_100',
      title: 'انگشت‌طلا',
      description: '۱۰۰ پاسخ درست تایپی',
      metric: AchievementMetric.typingCorrect,
      target: 100,
      emoji: '⌨️',
      xpReward: 150,
      tier: 2,
    ),
    Achievement(
      id: 'sentence_25',
      title: 'جمله‌ساز',
      description: '۲۵ جمله‌ی درست بساز',
      metric: AchievementMetric.sentenceCorrect,
      target: 25,
      emoji: '🧩',
      xpReward: 140,
      tier: 2,
    ),
    Achievement(
      id: 'minutes_300',
      title: 'پنج ساعت مطالعه',
      description: '۳۰۰ دقیقه در اپلیکیشن تمرین کن',
      metric: AchievementMetric.studyMinutes,
      target: 300,
      emoji: '⏳',
      xpReward: 200,
      tier: 2,
    ),
    Achievement(
      id: 'bookmarks_25',
      title: 'کلکسیونر',
      description: '۲۵ واژه را نشان کن',
      metric: AchievementMetric.bookmarkedWords,
      target: 25,
      emoji: '🔖',
      xpReward: 90,
      tier: 1,
    ),
    Achievement(
      id: 'ai_25',
      title: 'گفت‌وگو با دستیار',
      description: '۲۵ پیام با دستیار هوشمند رد و بدل کن',
      metric: AchievementMetric.aiChatMessages,
      target: 25,
      emoji: '🤖',
      xpReward: 110,
      tier: 2,
    ),
    Achievement(
      id: 'daily_30',
      title: 'یک روز پرکار',
      description: 'در یک روز ۳۰ واژه را تمرین کن',
      metric: AchievementMetric.wordsInOneDay,
      target: 30,
      emoji: '🚀',
      xpReward: 130,
      tier: 2,
    ),
    Achievement(
      id: 'reviews_30_day',
      title: 'روز طلایی',
      description: 'در یک روز ۶۰ مرور انجام بده',
      metric: AchievementMetric.wordsInOneDay,
      target: 60,
      emoji: '🥇',
      xpReward: 250,
      tier: 3,
      premium: false,
    ),
  ];

  static Achievement? byId(String id) {
    for (final achievement in all) {
      if (achievement.id == id) return achievement;
    }
    return null;
  }
}
